name: 24/7 Professional Amazon Stream
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # ئەم کرۆن جۆبە وای لێدەکات هەر ٣ کاتژمێر جارێک خۆکارانە کار بکاتەوە
    - cron: '0 */3 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # زۆرترین کات ٣ کاتژمێرە
    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
      - name: Start Black Screen Stream
        env:
          YOUTUBE_URL: ${{ secrets.YOUTUBE_URL }}
          YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
        run: |
          # فەرمانی تەمەنی ستریمەکە بۆ ١٦٥ خولەک (٢ کاتژمێر و ٤٥ خولەک) دادەنێت بۆ ئەوەی پێش خولی داهاتوو بوەستێت
          timeout 165m ffmpeg -re \
          -f lavfi -i color=c=black:s=1280x720:r=30 \
          -f lavfi -i anullsrc=cl=stereo:r=44100 \
          -c:v libx264 -preset ultrafast -tune zerolatency -b:v 1000k \
          -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k \
          -f flv "${YOUTUBE_URL}/${YOUTUBE_KEY}"
